### ISSUE TITLE
Building on OSX causes paket errors

### ISSUE THREAD

**Issue by rachelreese** [fsprojects/Cricket#40]
It works fine on windows, but on OSX I'm getting paket install errors which break the build. 

/Users/rachel/Code/Third Party/Cricket/.paket/paket.targets: Error: Command 'mono --runtime=v4.0.30319 /Users/rachel/Code/Third Party/Cricket/.paket/paket.exe install' exited with code: 2. (Cricket)

**Comment by colinbull** [comment]
@rachelreese @plumhead  Does the latest build of this work on OS X?

**Comment by plumhead** [comment]
Build Yes:
All Tests run: No

Detail below:


Tests run: 98, Errors: 0, Failures: 1, Inconclusive: 0, Time: 8.677544
seconds

  Not run: 3, Invalid: 0, Ignored: 3, Skipped: 0


Errors and Failures:

1) Test Failure : Cricket.Tests.Given an Message Handler.I can scan for a
message

   No result timeout

at Cricket.Tests.Given an Message Handler.I can scan for a message ()
[0x00000] in <filename unknown>:0



Tests Not Run:

1) Ignored : Cricket.Tests.Given an event stream.I can remove a
subscription post and subscribe to events by key

   Failing on build servers

2) Ignored : Cricket.Tests.Given an event stream.I can remove a
subscription post and subscribe to events by type

   Failing on build servers

3) Ignored : Cricket.Tests.Given an Message Handler.I can recieve a message

   Failing on build servers


Running build failed.

Error:

System.Exception: NUnit test failed (1).

  at Fake.NUnitSequential.NUnit (Microsoft.FSharp.Core.FSharpFunc`2
setParams, IEnumerable`1 assemblies) [0x00000] in <filename unknown>:0

  at FSI_0001.Build+clo@95-7.Invoke (Microsoft.FSharp.Core.Unit _arg5)
[0x00000] in <filename unknown>:0

  at Fake.TargetHelper+targetFromTemplate@145[Microsoft.FSharp.Core.Unit].Invoke
(Microsoft.FSharp.Core.Unit unitVar0) [0x00000] in <filename unknown>:0

  at Fake.TargetHelper.runTarget@314 (System.String targetName) [0x00000]
in <filename unknown>:0


---------------------------------------------------------------------

Build Time Report

---------------------------------------------------------------------

Target            Duration

------            --------

Clean             00:00:00.0103774

RestorePackages   00:00:00.0711791

AssemblyInfo      00:00:00.0094526

Build             00:00:24.0219756

Total:            00:00:36.9810771

Status:           Failure

---------------------------------------------------------------------

  1) System.Exception: NUnit test failed (1).

  at Fake.NUnitSequential.NUnit (Microsoft.FSharp.Core.FSharpFunc`2
setParams, IEnumerable`1 assemblies) [0x00000] in <filename unknown>:0

  at FSI_0001.Build+clo@95-7.Invoke (Microsoft.FSharp.Core.Unit _arg5)
[0x00000] in <filename unknown>:0

  at Fake.TargetHelper+targetFromTemplate@145[Microsoft.FSharp.Core.Unit].Invoke
(Microsoft.FSharp.Core.Unit unitVar0) [0x00000] in <filename unknown>:0

  at Fake.TargetHelper.runTarget@314 (System.String targetName) [0x00000]
in <filename unknown>:0

---------------------------------------------------------------------

**Comment by colinbull** [comment]
@plumhead is that with the latest? They pass on travis.??

**Comment by plumhead** [comment]
Clean pull from master.

**Comment by colinbull** [comment]
Fixed...
