### ISSUE TITLE
Q: What would be the equavalient?

### ISSUE THREAD

**Issue by haf** [fsprojects/Cricket#46]
```
/// The main protocol to talk to metric instances with
type MetricMsg =
  /// The GetValue implementation shall retrieve the value of one or more data
  /// points from the probe.
  | GetValue of DP list * ReplyChannel<Measure list>
```

What would be the 'catch it' equivalent of `Message.reply`?

**Comment by colinbull** [comment]
Not really sure what `catch it` means? Do you mean exception handling? Or something else?

**Comment by haf** [comment]
This https://github.com/fsprojects/Cricket/issues/47... You've already answered it! Thanks!
