### ISSUE TITLE
Q: Logging from actors

### ISSUE THREAD

**Issue by MBrouns** [fsprojects/Cricket#48]
I've been using Cricket for a little while now and so far i'm quite impressed. However, there are some simple things I haven't been able to properly figure out yet. One of these things is how to properly log messages from within actors. I found the logger class but it was unclear to me how this logger could be accessed from within an actor. Can this be done?

**Comment by colinbull** [comment]
There is the Tracing Module, which you can use to capture messages. The messages are captured in a dapper-esque format. There is a basic example [here](https://github.com/fsprojects/Cricket/blob/master/docs/content/diagnostics_tracing.fsx), let me know if that is what your looking for.

**Comment by MBrouns** [comment]
I'll check it out. Thanks for the help!
