### ISSUE TITLE
API Reference missing?

### ISSUE THREAD

**Issue by slav** [fsprojects/Cricket#50]
Hello. It seems all links to the API reference are missing. For example: https://fsprojects.github.io/Cricket/reference/cricket-actorconfiguration-1.html

And they would be very helpful to try to learn Cricket faster. Do the pages exist somewhere?

**Comment by colinbull** [comment]
I must of broken the build at some point, I'll look at re-instating this, this weekend.

**Comment by anishpateluk** [comment]
Any movement on this issue?

**Comment by colinbull** [comment]
I'm just having a look at this now, It seems like there is an issue in FSharp.Formatting. The is preventing the docs being created.

**Comment by colinbull** [comment]
Should be available now @ http://fsprojects.github.io/Cricket/reference/index.html. Reopen if not

**Comment by anishpateluk** [comment]
Thanks bud
