### ISSUE TITLE
PostAndReply?

### ISSUE THREAD

**Issue by slav** [fsprojects/Cricket#51]
It seems like right now it's only possible to reply to a message if another Actor sent it (by basically sending a message back). Are there any plans to add support for PostAndReply?

**Comment by colinbull** [comment]
From issue #36.

I have thought about this, numerous times. However I have come to the conclusion that they are somewhat orthogonal to location transparency and remoting. I do agree that they are probably useful within process thou. To this end I have a `AsyncResultCell<'a>` type [here](https://github.com/fsprojects/FSharp.Actor/blob/master/src/FSharp.Actor/Async.fs#L101) that will allow you to implement something similar to the methods you require. 

     type Message = 
             | Message of string * AsyncResultCell<int>

    type Parser() = 
          let actor = 
                actor {
                     messageHandler (fun ctx -> 
                          let rec loop() = async {
                               let! msg = ctx.Receive()
                                match msg.Message with
                                | Message(str, reply) -> reply.SetResult(Int32.Parse(str))
                                return! loop()
                          }
                          loop()
                    )
                }
     
      member x.ParseAsync str = async {
                let resultChannel = new AsyncResultCell<_>()
                actor <-- Message(str, resultChannel)
                return! resultChannel.AwaitResult() 
           }

      member x.Parse str = x.ParseAsync str |> Async.RunSynchronously

However, I'm not opposed to actually adding this to the API. I just need a good story for the remoting side as-well. 

Maybe it would be worth adding the PostAndReply variants as extension methods on ActorRef and possibly ActorSelection, where it makes sense. As I have been asked about this feature alot. 

I'm open to discussion on this, and any fresh ideas would be welcomed.

**Comment by colinbull** [comment]
Closing as I haven't heard anything
